//
//  HealthlyHabitsData.swift
//  Chabit-1.0
//
//  Created by Fauzi Fauzi on 20/07/19.
//  Copyright © 2019 C2G10. All rights reserved.
//

import Foundation

class HealthlyHabitsData {
    var data = ["Do housework", "Take 30-minute early morning", "Take 30 minute early morning walks",
                "Implement the two-minute walking habit for every hour that you sit",
                "Take the stairs instead of the elevator",
                "Walk whenever you can",
                "Use a treadmill desk",
                "Use a height-adjustable desk",
                "Aim for 10,000 steps a day Wear a step-tracking device",
                "Take a dance break",
                "Go hiking more often",
                "Do yoga",
                "Go rock climbing",
                "Go geocaching",
                "Workout during TV commercials",
                "Do some Deskercise",
                "Don't go to sleep angry",
                "Focus on understanding yourself instead of blaming others",
                "Live in the present instead of being stuck in the past",
                "Do it for yourself and your own peace of mind",
                "Remember the times when you were forgiven",
                "Remember people when they were children",
                "Remember why you love people",
                "Remember that it's better to be kind instead of right",
                "Observe, don't judge",
                "Take responsibility for your own shortcomings",
                "Acknowledge your growth from the experience",
                "Avoid eating when feeling stressed",
                "Use portion-control containers to store your meals",
                "Use portion-control plates when eating at home",
                "Listen to your hunger cues",
                "Drink plenty of water and healthy fluids",
                "Keep a food diary or journal",
                "Make and drink healthy smoothies",
                "Learn how to read nutrition labels",
                "Stay away from fun-size candy bars and other treats",
                "Plan your meals every week",
                "Make your own single-serving snack packs",
                "Limit distractions during meal times",
                "Take probiotics daily",
                "Stick to your grocery list",
                "Try turmeric supplements",
                "Take smaller bites and eat slowly",
                "Chew your food at least five times before swallowing",
                "Drink before you get thirsty",
                "Annual physical exam",
                "Thyroid test (for women only)",
                "Bone mineral density test (women)",
                "Mammogram (women)",
                "Colonoscopy",
                "Fasting plasma glucose test",
                "Eye exam",
                "Hearing test",
                "Dental exam and cleaning",
                "Abdominal aortic aneurysm screening (for men only)",
                "Blood pressure screening",
                "Cholesterol screening",
                "Prostate screening (men)",
                "Lung cancer screening",
                "Testicular self-exam (men)",
                "Pap test and HPV test (women)",
                "Chlamydia test (women)",
                "Gonorrhea test (women)",
                "HIV test and other sexually transmitted infection tests",
                "Skin exams",
                "Influenza (flu) vaccine",
                "Hepatitis A vaccine",
                "Hepatitis B vaccine",
                "Herpes zoster vaccine",
                "Human papillomavirus (HPV) vaccine",
                "MMR (measles, mumps, rubella)",
                "Meningococcal (meningitis)",
                "Pneumonia vaccine",
                "Tetanus, diphtheria, pertussis",
                "Varicella (chicken pox)"]
}

